// lang/lang.ts
export const sfm_languages = {
  en: {
    submit: 'Submit',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    warning: 'Warning',
    selectFilesBtn: 'Select Files',
    clearBtn: 'Clear',

    createFile: 'Create File',
    createFolder: 'Create Folder',
    rename: 'Rename',
    upload: 'Upload',
    download: 'Download',
    search: 'Search',
    copy: 'Copy',
    move: 'Move',
    paste: 'Paste',
    compress: 'Compress',
    extract: 'Extract',
    permissions: 'Permissions',
    delete: 'Delete',
    name: 'Name',
    size: 'Size',
    modifiedAt: 'Modified At',
    actions: 'Actions',
    open: 'Open',
    select: 'Select',
    location: 'Location',

    pathOperationError: 'Path operation not allowed. Please switch to another path.',
    pasteSuccess: 'Paste success',
    compressSuccess: 'Compress success',
    uncompressSuccess: 'Uncompress success',
    confirmDelete: 'Are you sure to delete the selected files?',
    deleteCode: 'Please enter the verification code for deleting files',
    inputError: 'Input Error',
    deleteSuccess: 'Delete success',
    selectFiles: 'Please select files',

    fileName: 'File Name',
    enterFileName: 'Please enter the file name',
    createFileSuccess: 'File created successfully',
    renameSuccess: 'Rename success',

    folderName: 'Folder Name',
    enterFolderName: 'Please enter the folder name',
    createFolderSuccess: 'Folder created successfully',

    owner: 'Owner',
    group: 'User Group',
    public: 'Public',
    read: 'Read',
    write: 'Write',
    execute: 'Executable',
    modifySubfiles: 'Modify permissions for subfiles recursively',
    modifyPermissionsSuccess: 'Permissions modified successfully',

    uploadFile: 'Upload File',
    uploadFolder: 'Upload Folder',
    clickToUpload: 'Click to select or drag files/folders here',
    supportMultiUpload: 'Support multiple files and directories',
    uploadCompleted: 'Upload completed',
    uploadTimeout: 'Upload timeout',
    uploadFailed: 'Upload failed',
    uploadError: 'An upload error occurred',

    saveFileSuccess: 'Save file success',
  },
  zhCn: {
    submit: '提交',
    cancel: '取消',
    close: '关闭',
    confirm: '确认',
    warning: '警告',
    selectFilesBtn: '选择文件',
    clearBtn: '清空',

    createFile: '创建文件',
    createFolder: '创建文件夹',
    rename: '重命名',
    upload: '上传',
    download: '下载',
    search: '搜索',
    copy: '复制',
    move: '移动',
    paste: '粘贴',
    compress: '压缩',
    extract: '解压',
    permissions: '权限',
    delete: '删除',
    name: '名称',
    size: '大小',
    modifiedAt: '修改时间',
    actions: '操作',
    open: '打开',
    select: '选择',
    location: '定位',

    pathOperationError: '无法操作该路径，请切换到其他路径',
    pasteSuccess: '粘贴成功',
    compressSuccess: '压缩文件成功',
    uncompressSuccess: '解压成功',
    confirmDelete: '确定删除所选文件吗？',
    deleteCode: '请输入删除文件验证码',
    inputError: '输入错误',
    deleteSuccess: '删除成功',
    selectFiles: '请选择文件',

    fileName: '文件名',
    enterFileName: '请输入文件名',
    createFileSuccess: '创建文件成功',
    renameSuccess: '重命名成功',

    folderName: '文件夹名',
    enterFolderName: '请输入文件夹名',
    createFolderSuccess: '创建文件夹成功',

    owner: '所有者',
    group: '用户组',
    public: '公共',
    read: '读取',
    write: '写入',
    execute: '可执行',
    modifySubfiles: '同时修改子文件权限',
    modifyPermissionsSuccess: '权限修改成功',

    uploadFile: '上传文件',
    uploadFolder: '上传文件夹',
    clickToUpload: '点击选择或拖拽文件/文件夹到这里',
    supportMultiUpload: '支持多文件和目录',
    uploadCompleted: '上传完成',
    uploadTimeout: '上传超时',
    uploadFailed: '上传失败',
    uploadError: '上传发生错误',

    saveFileSuccess: '保存文件成功',

    searchNoQuery: '请输入搜索内容',
  },
};


