// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetURL():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenMultipleFilesDialog(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;
